In [3]:
import torch
import torch.nn as nn
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

In [4]:
train_data = datasets.CIFAR10(
    root = "data",   # nereye yükleyeceğiz (data klasörü)
    train = True,
    download = True,    # data zaten yüklü değilse yükle
    transform = transforms.ToTensor(),   # PIL formatında gelen imageleri torch tensor yapar
    target_transform=None   #  you can transform labels as well if needed  (ZATEN NONE gelir)
    )

test_data = datasets.CIFAR10(
    root = "data",   
    train = False,  # test data
    download = True,    
    transform = transforms.ToTensor(),
    )

Files already downloaded and verified
Files already downloaded and verified


In [5]:
image, label = train_data[0]

In [6]:
image

tensor([[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
         [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
         [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
         ...,
         [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
         [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
         [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],

        [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
         [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
         [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
         ...,
         [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
         [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
         [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],

        [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
         [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
         [0.0824, 0.0000, 0.0314,  ..., 0.1961, 0.1961, 0.

In [7]:
label

6

In [8]:
image.shape

torch.Size([3, 32, 32])

In [9]:
len(train_data), len(test_data)

(50000, 10000)

In [10]:
class_names = train_data.classes
class_names

['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [11]:
"""
#image, label = train_data[0]
#plt.imshow(image)
#plt.title(label)
# this will give you an error of 
# TypeError: Invalid shape (3, 32, 32) for image data -- 32,32,3 yapmalıyız
"""

'\n#image, label = train_data[0]\n#plt.imshow(image)\n#plt.title(label)\n# this will give you an error of \n# TypeError: Invalid shape (3, 32, 32) for image data -- 32,32,3 yapmalıyız\n'

In [ ]:
image, label = train_data[1]
image = image.permute(1,2,0)
plt.figure(figsize = (2, 2))
plt.imshow(image)
plt.title(class_names[label])

Text(0.5, 1.0, 'truck')

In [13]:
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.491, 0.482, 0.446],     # buradaki değerler datasetin ortalaması ve 
        std=[0.247, 0.243, 0.261]       # standart sapmasıdır.
    )
])

CIFAR10 dataset’i 50.000 eğitim görüntüsünden oluşur. Her görüntü: 3 kanal (R, G, B) ve boyut 32×32.

Bu sayılar, CIFAR10 dataset’inin tüm eğitim seti üzerinde hesaplanmış istatistiklerdir.

Yani: • mean (RGB): [0.491, 0.482, 0.446] → CIFAR10 görüntülerinin kırmızı, yeşil ve mavi kanallarının ortalaması. • std (RGB): [0.247, 0.243, 0.261] → Aynı kanalların standart sapması.

CNN’ler, özellikle Adam ve SGD gibi optimizasyon algoritmaları, standartlaştırılmış girişlerle çok daha iyi öğrenir.

Normalize edilmemiş görüntü: • Piksel değerleri 0–255 arasında düzensiz dağılmış • Kanal başına farklı ortalamalar • Modelin ilk katmanı için öğrenme zorlaşır

Normalize edilmiş görüntü: • Tüm görüntünün ortalaması ~ 0 • Dağılımın genişliği ~ 1 • Tüm kanallar daha benzer ölçeğe sahip

Bu: • Modelin hızlı öğrenmesini sağlar • daha stabil loss • Gradientlerin daha “dengeli” akması • Yüksek learning rate’lerin çalışabilmesi • Genel accuracy’nin ciddi şekilde artması

In [14]:
from torch.utils.data import DataLoader

In [15]:
BATCH_SIZE = 32

train_dataloader = DataLoader(
    train_data,
    batch_size = BATCH_SIZE,    # her batchde kaç örnek olacak
    shuffle = True      # karıştırır train datasını
)

test_dataloader = DataLoader(
    test_data,
    batch_size = BATCH_SIZE,    # her batchde kaç örnek olacak
    shuffle = False      # test datasını karıştırmaya gerek yok
)

In [16]:
print(f"Length of train dataloader: {len(train_dataloader)} batches of {BATCH_SIZE}")
print(f"Length of test dataloader: {len(test_dataloader)} batches of {BATCH_SIZE}")

Length of train dataloader: 1563 batches of 32
Length of test dataloader: 313 batches of 32


In [22]:
train_dataloader.dataset[0][0].shape

torch.Size([3, 32, 32])